import { useMemo, useRef, useState } from 'react';
import { VizPanel, Segmented, Slider, Choice, Check, Button, Legend, Stats, Note, useTicker, makeRng, fmtNum } from './Viz';

/**
 * Three ways to answer "what is the rank of key x in this sorted set?", built over the same keys.
 *
 * Model assumptions (all labelled in the UI where a number appears):
 *  - Keys are distinct 8-byte unsigned integers generated by a gap process per distribution.
 *  - Cost is counted in memory probes: distinct 64-byte cache lines a cold lookup reads. A binary
 *    search over L cache lines touches about ceil(log2 L) + 1 of them.
 *  - B+tree: bulk-loaded, every node full with F entries. Leaves hold the 8-byte keys (the sorted
 *    array cut into nodes); inner entries are an 8-byte separator plus an 8-byte child pointer. Each
 *    inner node costs the binary search over its separators plus one line for the child pointer.
 *  - RMI (Kraska et al. 2018): two stages of linear models. The root predicts a position and picks one
 *    of M leaf models with floor(M * f0(x) / N); each leaf stores slope, intercept and how far
 *    below and above its prediction a key's true rank fell (24 bytes). The search window is [pred - below, pred + above], searched with a
 *    model-biased binary search (first probe at the prediction). Probes: root model line + leaf model
 *    line + the lines the window search touches. The keys stay in a dense 8-byte array.
 *  - After appends the models are NOT retrained. The lab recomputes the window each leaf would now need
 *    for every stored key to be found — a real static RMI has no such bound without a rebuild, which is
 *    why systems add a delta buffer or retrain.
 *  - Elias-Fano (Elias 1974, as in Vigna's quasi-succinct indices and folly's EliasFanoCoding.h):
 *    l = floor(log2(u/n)) low bits verbatim; high parts as unary gaps in (u >> l) + n bits. select0 is
 *    served by one 32-bit sample every 256 zeros plus a popcount scan; rank counters are drawn Rank9-style
 *    (a 64-bit count every 512 bits, a 9-bit count per 64-bit word).
 */

/* ------------------------------------------------------------------ keys */

export type Dist = 'uniform' | 'zipf' | 'clustered' | 'sequential';
export type AppendKind = 'same' | 'sparse' | 'burst';

export const DIST_LABEL: Record<Dist, string> = {
  uniform: 'Uniform random',
  zipf: 'Zipf-like gaps (heavy tail)',
  clustered: 'Clustered timestamps',
  sequential: 'Sequential ids',
};

const SEED: Record<Dist, number> = { uniform: 11, zipf: 23, clustered: 37, sequential: 41 };
const UNIFORM_MEAN_GAP = 2 ** 20;
const ZIPF_CAP = 2 ** 24;

type GapGen = () => number;

/** A gap process per distribution. `scale` multiplies every gap (10 = keys arrive ten times more spread out). */
function gapGen(dist: Dist, seed: number, scale = 1): GapGen {
  const rng = makeRng(seed);
  const u01 = () => rng() + 0.5e-6; // strictly inside (0, 1)
  if (dist === 'uniform') return () => Math.max(1, Math.round(-Math.log(1 - rng() * 0.999999) * UNIFORM_MEAN_GAP * scale));
  if (dist === 'zipf') return () => Math.max(1, Math.round(Math.min(ZIPF_CAP, Math.floor(u01() ** -2)) * scale));
  if (dist === 'sequential') return () => Math.max(1, Math.round((rng() < 0.95 ? 1 : 2 + Math.floor(rng() * 20)) * scale));
  // clustered timestamps, in milliseconds: bursts of 50-400 events ~20 ms apart, separated by idle gaps averaging an hour
  let left = 0;
  return () => {
    if (left <= 0) {
      left = 50 + Math.floor(rng() * 350);
      return Math.max(1, Math.round(-Math.log(1 - rng() * 0.999999) * 3_600_000 * scale));
    }
    left--;
    return Math.max(1, Math.round(-Math.log(1 - rng() * 0.999999) * 20 * scale));
  };
}

export function genKeys(dist: Dist, n: number): number[] {
  const g = gapGen(dist, SEED[dist]);
  const keys = new Array<number>(n);
  let k = 0;
  for (let i = 0; i < n; i++) {
    k += g();
    keys[i] = k;
  }
  return keys;
}

function mergeSorted(a: number[], b: number[]) {
  const out = new Array<number>(a.length + b.length);
  let i = 0;
  let j = 0;
  let o = 0;
  while (i < a.length && j < b.length) out[o++] = a[i] <= b[j] ? a[i++] : b[j++];
  while (i < a.length) out[o++] = a[i++];
  while (j < b.length) out[o++] = b[j++];
  return out;
}

/** New keys for one append. Returns them sorted and distinct from `keys`. */
export function appendBatch(keys: number[], dist: Dist, kind: AppendKind, batch: number, seed: number): number[] {
  const out: number[] = [];
  if (kind === 'burst') {
    // A hot range: the free integers nearest the key at 40% of the ranks, taken as consecutive values.
    const c = Math.floor(keys.length * 0.4);
    for (let d = 0; out.length < batch && d < keys.length; d++) {
      for (const i of d === 0 ? [c] : [c - d, c + d]) {
        if (i < 0 || i >= keys.length - 1 || out.length >= batch) continue;
        for (let v = keys[i] + 1; v < keys[i + 1] && out.length < batch; v++) out.push(v);
      }
    }
    return out.sort((x, y) => x - y);
  }
  const g = gapGen(dist, seed, kind === 'sparse' ? 10 : 1);
  let k = keys[keys.length - 1];
  for (let i = 0; i < batch; i++) {
    k += g();
    out.push(k);
  }
  return out;
}

/* ------------------------------------------------------------ cost model */

export const LINE_BYTES = 64;
export const KEY_BYTES = 8;

/** Distinct cache lines a binary search over `entries` 8-byte values touches. */
export function searchLines(entries: number) {
  const lines = Math.ceil((Math.max(1, entries) * KEY_BYTES) / LINE_BYTES);
  return lines <= 1 ? 1 : Math.ceil(Math.log2(lines)) + 1;
}

const cmpCount = (entries: number) => (entries <= 1 ? 1 : Math.ceil(Math.log2(entries)));

/* --------------------------------------------------------------- B+tree */

export function bptree(n: number, F: number) {
  const counts = [Math.max(1, Math.ceil(n / F))]; // leaves
  while (counts[counts.length - 1] > 1) counts.push(Math.ceil(counts[counts.length - 1] / F));
  const height = counts.length; // including the leaf level
  let innerBytes = 0;
  for (let l = 1; l < counts.length; l++) innerBytes += counts[l - 1] * 2 * KEY_BYTES;
  // cost per level, root first
  const levels: { nodes: number; entries: number; lines: number; comparisons: number; inner: boolean }[] = [];
  for (let l = counts.length - 1; l >= 0; l--) {
    const inner = l > 0;
    const entries = inner ? Math.min(F, counts[l - 1]) : Math.min(F, n);
    levels.push({ nodes: counts[l], entries, lines: searchLines(entries) + (inner ? 1 : 0), comparisons: cmpCount(entries), inner });
  }
  const probes = levels.reduce((s, x) => s + x.lines, 0);
  const comparisons = levels.reduce((s, x) => s + x.comparisons, 0);
  return { height, levels, innerBytes, bytesPerKey: KEY_BYTES + innerBytes / n, overheadPerKey: innerBytes / n, probes, comparisons };
}

/** Node index visited at each level (root first) for the key at rank r. */
export function bptreePath(r: number, F: number, height: number) {
  const path: number[] = [];
  for (let l = height - 1; l >= 0; l--) path.push(Math.floor(r / F ** (l + 1)));
  return path;
}

/* ------------------------------------------------------------------- RMI */

export type Leaf = { a: number; b: number; start: number; count: number; below: number; above: number };
export type Rmi = { M: number; nTrain: number; kmin: number; kspan: number; a0: number; b0: number; leaves: Leaf[] };

function fit(keys: number[], from: number, to: number, kmin: number, kspan: number) {
  const n = to - from;
  if (n <= 0) return { a: from, b: 0 };
  if (n === 1) return { a: from, b: 0 };
  let sx = 0;
  let sy = 0;
  for (let i = from; i < to; i++) {
    sx += (keys[i] - kmin) / kspan;
    sy += i;
  }
  const mx = sx / n;
  const my = sy / n;
  let sxy = 0;
  let sxx = 0;
  for (let i = from; i < to; i++) {
    const dx = (keys[i] - kmin) / kspan - mx;
    sxy += dx * (i - my);
    sxx += dx * dx;
  }
  const b = sxx > 0 ? sxy / sxx : 0;
  return { a: my - b * mx, b };
}

export const route = (m: Rmi, x: number) => {
  const xn = (x - m.kmin) / m.kspan;
  const p = m.a0 + m.b0 * xn;
  return Math.min(m.M - 1, Math.max(0, Math.floor((m.M * p) / m.nTrain)));
};

export const predict = (m: Rmi, x: number, n: number) => {
  const leaf = m.leaves[route(m, x)];
  const xn = (x - m.kmin) / m.kspan;
  return Math.min(n - 1, Math.max(0, Math.round(leaf.a + leaf.b * xn)));
};

/** Train a two-stage linear RMI on `keys`, recording how far below and above its prediction each leaf's keys fell. */
export function trainRmi(keys: number[], M: number): Rmi {
  const n = keys.length;
  const kmin = keys[0];
  const kspan = Math.max(1, keys[n - 1] - keys[0]);
  const root = fit(keys, 0, n, kmin, kspan);
  const m: Rmi = { M, nTrain: n, kmin, kspan, a0: root.a, b0: root.b, leaves: [] };
  // the root is monotone (slope >= 0), so each leaf receives a contiguous run of ranks
  const starts = new Array<number>(M + 1).fill(-1);
  let i = 0;
  for (let j = 0; j < M; j++) {
    starts[j] = i;
    while (i < n && route(m, keys[i]) === j) i++;
  }
  starts[M] = n;
  for (let j = 0; j < M; j++) {
    const f = fit(keys, starts[j], starts[j + 1], kmin, kspan);
    m.leaves.push({ ...f, start: starts[j], count: starts[j + 1] - starts[j], below: 0, above: 0 });
  }
  const errs = leafErrors(keys, m);
  m.leaves.forEach((l, j) => {
    l.below = errs[j].below;
    l.above = errs[j].above;
  });
  return m;
}

/** The window each leaf needs so that every key now stored is found: how far below (over-prediction) and above (under-prediction) the prediction a true rank lies. */
export function leafErrors(keys: number[], m: Rmi) {
  const errs = m.leaves.map(() => ({ below: 0, above: 0, count: 0 }));
  const n = keys.length;
  for (let i = 0; i < n; i++) {
    const j = route(m, keys[i]);
    const d = i - predict(m, keys[i], n);
    const e = errs[j];
    e.count++;
    if (d > e.above) e.above = d;
    if (-d > e.below) e.below = -d;
  }
  return errs;
}

export function rmiCost(keys: number[], m: Rmi) {
  const n = keys.length;
  const errs = leafErrors(keys, m);
  let probeSum = 0;
  let cmpSum = 0;
  let maxWindow = 1;
  let windowSum = 0;
  for (let i = 0; i < n; i++) {
    const j = route(m, keys[i]);
    const p = predict(m, keys[i], n);
    const w = Math.min(n - 1, p + errs[j].above) - Math.max(0, p - errs[j].below) + 1;
    windowSum += w;
    if (w > maxWindow) maxWindow = w;
    probeSum += 2 + searchLines(w);
    cmpSum += cmpCount(w) + 1;
  }
  const modelBytes = 16 + 24 * m.M;
  return {
    errs,
    avgProbes: probeSum / n,
    avgComparisons: cmpSum / n,
    avgWindow: windowSum / n,
    maxWindow,
    modelBytes,
    bytesPerKey: KEY_BYTES + modelBytes / n,
    overheadPerKey: modelBytes / n,
  };
}

export type SearchStep = { lo: number; hi: number; mid: number; less: boolean };

/** Model-biased binary search for lower_bound(x) inside the window. */
export function rmiLookup(keys: number[], m: Rmi, errs: { below: number; above: number }[], x: number) {
  const n = keys.length;
  const leaf = route(m, x);
  const pred = predict(m, x, n);
  const lo = Math.max(0, pred - errs[leaf].below);
  const hi = Math.min(n - 1, pred + errs[leaf].above);
  let L = lo;
  let R = hi + 1;
  const steps: SearchStep[] = [];
  let first = true;
  while (L < R) {
    const mid = first ? Math.min(R - 1, Math.max(L, pred)) : (L + R) >> 1;
    first = false;
    const less = keys[mid] < x;
    steps.push({ lo: L, hi: R - 1, mid, less });
    if (less) L = mid + 1;
    else R = mid;
  }
  const window = hi - lo + 1;
  return { leaf, pred, lo, hi, window, steps, rank: L, probes: 2 + searchLines(window) };
}

/* ----------------------------------------------------------- Elias-Fano */

export const SELECT_SAMPLE = 256;

export type EF = { n: number; u: number; l: number; upper: Uint8Array; lower: number[]; zeroSamples: number[]; bits: number; upperBits: number; lowerBits: number; sampleBits: number };

export function buildEF(keys: number[]): EF {
  const n = keys.length;
  const u = keys[n - 1];
  let l = 0;
  while (2 ** (l + 1) * n <= u) l++;
  const pow = 2 ** l;
  const upperLen = Math.floor(u / pow) + n;
  const upper = new Uint8Array(upperLen);
  const lower = new Array<number>(n);
  for (let i = 0; i < n; i++) {
    const h = Math.floor(keys[i] / pow);
    upper[h + i] = 1;
    lower[i] = keys[i] - h * pow;
  }
  // position just after every SELECT_SAMPLE-th zero
  const zeroSamples = [0];
  let zeros = 0;
  for (let p = 0; p < upperLen; p++) {
    if (!upper[p]) {
      zeros++;
      if (zeros % SELECT_SAMPLE === 0) zeroSamples.push(p + 1);
    }
  }
  const sampleBits = (zeroSamples.length - 1) * 32;
  return { n, u, l, upper, lower, zeroSamples, upperBits: upperLen, lowerBits: n * l, sampleBits, bits: upperLen + n * l + sampleBits };
}

/** Position just after the v-th zero (0 for v = 0), and where the sampled scan started. */
export function select0(ef: EF, v: number) {
  const s = Math.min(Math.floor(v / SELECT_SAMPLE), ef.zeroSamples.length - 1);
  const from = ef.zeroSamples[s];
  let p = from;
  let zeros = s * SELECT_SAMPLE;
  while (zeros < v && p < ef.upper.length) {
    if (!ef.upper[p]) zeros++;
    p++;
  }
  return { pos: p, from, sample: s };
}

export function efAccess(ef: EF, i: number) {
  // select1(i): position of the i-th one (0-based), by a linear scan — the lab only uses it to check decoding
  let ones = -1;
  let p = 0;
  for (; p < ef.upper.length; p++) if (ef.upper[p] && ++ones === i) break;
  return (p - i) * 2 ** ef.l + ef.lower[i];
}

export function rank9(ef: EF, p: number) {
  const blockStart = Math.floor(p / 512) * 512;
  const wordStart = Math.floor(p / 64) * 64;
  let block = 0;
  let word = 0;
  let inWord = 0;
  for (let q = 0; q < p; q++) {
    if (!ef.upper[q]) continue;
    if (q < blockStart) block++;
    else if (q < wordStart) word++;
    else inWord++;
  }
  return { blockStart, wordStart, block, word, inWord, rank: block + word + inWord };
}

function efProbeLines(ef: EF, scanned: number, examined: number) {
  return 1 + Math.ceil((scanned + 1) / 512) + Math.floor(examined / 512) + (ef.l > 0 ? Math.ceil((Math.max(1, examined) * ef.l) / 512) : 0);
}

/** lower_bound(x): the rank of the first key >= x. */
export function efLookup(ef: EF, x: number) {
  const pow = 2 ** ef.l;
  const v = Math.floor(x / pow);
  const xl = x - v * pow;
  if (v > Math.floor(ef.u / pow)) return { v, xl, bucketStart: ef.upper.length, rank: ef.n, examined: 0, bucketSize: 0, scanned: 0, sample: 0, probes: 1 };
  const sel = select0(ef, v);
  let p = sel.pos;
  let i = p - v;
  let examined = 0;
  let bucketSize = 0;
  while (p + bucketSize < ef.upper.length && ef.upper[p + bucketSize]) bucketSize++;
  while (p < ef.upper.length && ef.upper[p]) {
    examined++;
    if (ef.lower[i] >= xl) break;
    p++;
    i++;
  }
  const scanned = sel.pos - sel.from;
  return { v, xl, bucketStart: sel.pos, rank: i, examined, bucketSize, scanned, sample: sel.sample, probes: efProbeLines(ef, scanned, examined) };
}

/** Average probes over lookups of every stored key, in one pass over the upper bits. */
export function efCost(ef: EF) {
  let probeSum = 0;
  let maxBucket = 0;
  let zeros = 0;
  let i = 0;
  let bucketStart = 0;
  let inBucket = 0;
  for (let p = 0; p < ef.upper.length; p++) {
    if (!ef.upper[p]) {
      zeros++;
      bucketStart = p + 1;
      inBucket = 0;
      continue;
    }
    inBucket++;
    if (inBucket > maxBucket) maxBucket = inBucket;
    const v = zeros;
    const from = ef.zeroSamples[Math.min(Math.floor(v / SELECT_SAMPLE), ef.zeroSamples.length - 1)];
    probeSum += efProbeLines(ef, bucketStart - from, inBucket);
    i++;
  }
  return { avgProbes: probeSum / Math.max(1, i), maxBucket, bytesPerKey: ef.bits / 8 / ef.n, bitsPerKey: ef.bits / ef.n };
}


/* ------------------------------------------------------------ simulation */

export type Op = { type: 'append'; kind: AppendKind; batch: number } | { type: 'retrain' };
export type HistoryPoint = { step: number; kind: 'build' | 'retrain' | AppendKind; n: number; rmi: number; btree: number; ef: number; retrained: boolean; rmiBeforeRetrain?: number };

export const MAX_KEYS = 60_000;
export const MAX_OPS = 30;

export type SimState = {
  dist: Dist;
  M: number;
  F: number;
  keys: number[];
  /** Keys added since the models were last trained (for drawing). */
  fresh: number[];
  model: Rmi;
  retrains: number;
  retrainScanned: number;
  appendedSinceTrain: number;
  history: HistoryPoint[];
  lastEvent: string;
  ops: number;
};

function measure(s: SimState, kind: HistoryPoint['kind'], retrained: boolean, before?: number): HistoryPoint {
  return {
    step: s.ops,
    kind,
    n: s.keys.length,
    rmi: rmiCost(s.keys, s.model).avgProbes,
    btree: bptree(s.keys.length, s.F).probes,
    ef: efCost(buildEF(s.keys)).avgProbes,
    retrained,
    rmiBeforeRetrain: before,
  };
}

export function initState(dist: Dist, n0: number, M: number, F: number): SimState {
  const keys = genKeys(dist, n0);
  const s: SimState = { dist, M, F, keys, fresh: [], model: trainRmi(keys, M), retrains: 0, retrainScanned: 0, appendedSinceTrain: 0, history: [], lastEvent: '', ops: 0 };
  s.history = [measure(s, 'build', false)];
  return s;
}

function retrain(t: SimState) {
  t.model = trainRmi(t.keys, t.M);
  t.retrains += 1;
  t.retrainScanned += t.keys.length;
  t.appendedSinceTrain = 0;
  t.fresh = [];
}

/** Apply one operation. Deterministic: the append's random stream is seeded by the operation's index. */
export function applyOp(s: SimState, op: Op, autoRetrain: boolean): SimState {
  if (s.ops >= MAX_OPS) return s;
  const t: SimState = { ...s, ops: s.ops + 1 };
  if (op.type === 'retrain') {
    retrain(t);
    t.lastEvent = `Retrained by hand: one pass over all ${fmtNum(t.keys.length)} keys refits every leaf and shrinks the windows back to the training error.`;
    t.history = [...s.history, measure(t, 'retrain', true)];
    return t;
  }
  const room = MAX_KEYS - t.keys.length;
  const add = appendBatch(t.keys, t.dist, op.kind, Math.max(0, Math.min(op.batch, room)), 1000 + s.ops * 7919);
  t.keys = mergeSorted(t.keys, add);
  t.fresh = mergeSorted(t.fresh, add);
  t.appendedSinceTrain += add.length;
  const cost = rmiCost(t.keys, t.model).avgProbes;
  const bt = bptree(t.keys.length, t.F).probes;
  if (autoRetrain && cost > bt) {
    retrain(t);
    t.lastEvent = `Retrain triggered: the stale windows cost ${fmtNum(cost, 1)} probes per lookup on average, more than the B+tree's ${bt}, so the RMI rescanned all ${fmtNum(t.keys.length)} keys and refit its ${t.M} leaves.`;
    t.history = [...s.history, measure(t, op.kind, true, cost)];
  } else {
    t.lastEvent = add.length === 0 ? 'No keys were added: the lab caps the set at 60,000 keys, or there is no free key left in that range.' : '';
    t.history = [...s.history, measure(t, op.kind, false)];
  }
  return t;
}

export function simulate(dist: Dist, n0: number, M: number, F: number, ops: Op[], autoRetrain: boolean) {
  let s = initState(dist, n0, M, F);
  for (const op of ops) s = applyOp(s, op, autoRetrain);
  return s;
}

/** For each leaf, the first and last rank of the keys it currently routes. */
export function leafRanges(keys: number[], m: Rmi) {
  const first = new Array<number>(m.M).fill(-1);
  const last = new Array<number>(m.M).fill(-1);
  for (let i = 0; i < keys.length; i++) {
    const j = route(m, keys[i]);
    if (first[j] < 0) first[j] = i;
    last[j] = i;
  }
  return { first, last };
}

/* -------------------------------------------------------------------- UI */

const DISTS: Dist[] = ['uniform', 'zipf', 'clustered', 'sequential'];
const APPEND_LABEL: Record<AppendKind, string> = {
  burst: 'Burst into one hot key range',
  same: 'Past the max, same pattern',
  sparse: 'Past the max, 10× sparser',
};
const C_BT = 'var(--viz-7)';
const C_EF = 'var(--viz-2)';
const C_RMI = 'var(--viz-3)';
const C_FRESH = 'var(--viz-4)';

function compact(v: number) {
  const a = Math.abs(v);
  if (a >= 1e9) return `${fmtNum(v / 1e9, 2)}B`;
  if (a >= 1e6) return `${fmtNum(v / 1e6, 2)}M`;
  if (a >= 1e4) return `${fmtNum(v / 1e3, 1)}K`;
  return fmtNum(v);
}

type Detail = 'rmi' | 'ef' | 'bt';

export default function RmiEliasFanoLab() {
  const [dist, setDist] = useState<Dist>('uniform');
  const [n0, setN0] = useState(5000);
  const [M, setM] = useState(64);
  const [F, setF] = useState(64);
  const [kind, setKind] = useState<AppendKind>('burst');
  const [batch, setBatch] = useState(1000);
  const [auto, setAuto] = useState(true);
  const [sim, setSim] = useState<SimState>(() => initState('uniform', 5000, 64, 64));
  const [rankPick, setRankPick] = useState(2000);
  const [picks, setPicks] = useState(0);
  const [detail, setDetail] = useState<Detail>('rmi');
  const [stage, setStage] = useState(99);
  const [running, setRunning] = useState(false);
  const acc = useRef(0);

  const rebuild = (d: Dist, n: number, m: number, f: number) => {
    setSim(initState(d, n, m, f));
    setStage(99);
    setRunning(false);
  };

  const keys = sim.keys;
  const N = keys.length;
  const rank = Math.min(rankPick, N - 1);
  const key = keys[rank];

  const rc = useMemo(() => rmiCost(sim.keys, sim.model), [sim]);
  const ef = useMemo(() => buildEF(sim.keys), [sim]);
  const ec = useMemo(() => efCost(ef), [ef]);
  const bt = useMemo(() => bptree(N, sim.F), [N, sim.F]);
  const ranges = useMemo(() => leafRanges(sim.keys, sim.model), [sim]);
  const look = useMemo(() => rmiLookup(sim.keys, sim.model, rc.errs, key), [sim, rc, key]);
  const efl = useMemo(() => efLookup(ef, key), [ef, key]);
  const r9 = useMemo(() => rank9(ef, efl.bucketStart), [ef, efl]);
  const path = bptreePath(rank, sim.F, bt.height);
  const eliasBound = 2 + Math.ceil(Math.log2(Math.max(1, ef.u / ef.n)));

  const maxStage = detail === 'rmi' ? 3 + look.steps.length : detail === 'ef' ? 4 : bt.height;
  const shown = (i: number) => stage >= i;

  useTicker((dt) => {
    acc.current += dt;
    if (acc.current < 650) return;
    acc.current = 0;
    if (stage + 1 >= maxStage) {
      setStage(99);
      setRunning(false);
    } else setStage(stage + 1);
  }, running);

  const append = () => {
    setSim((s) => applyOp(s, { type: 'append', kind, batch }, auto));
    setStage(99);
    setRunning(false);
  };
  const canAppend = sim.ops < MAX_OPS && N < MAX_KEYS;
  const kinds: AppendKind[] = dist === 'sequential' ? ['same', 'sparse'] : ['burst', 'same', 'sparse'];

  /* ---------- figure 1: meters and history ---------- */
  const W = 680;
  const structs = [
    { name: 'B+tree', color: C_BT, bytes: bt.bytesPerKey, probes: bt.probes },
    { name: 'Elias-Fano', color: C_EF, bytes: ec.bytesPerKey, probes: ec.avgProbes },
    { name: 'RMI', color: C_RMI, bytes: rc.bytesPerKey, probes: rc.avgProbes },
  ];
  const bytesMax = Math.max(9, ...structs.map((s) => s.bytes));
  const probeMax = Math.max(12, Math.min(40, Math.max(...structs.map((s) => s.probes))));
  const barX = 78;
  const barW = 170;

  const hist = sim.history;
  const hx0 = 360;
  const hx1 = W - 12;
  const hy0 = 22;
  const hy1 = 138;
  const hMaxX = Math.max(10, hist.length - 1);
  const hMaxY = Math.max(14, Math.min(40, Math.ceil(Math.max(...hist.map((h) => Math.max(h.rmi, h.btree, h.ef, h.rmiBeforeRetrain ?? 0))))));
  const hClipped = hist.some((h) => Math.max(h.rmi, h.btree, h.ef, h.rmiBeforeRetrain ?? 0) > hMaxY);
  const HX = (i: number) => hx0 + (i / hMaxX) * (hx1 - hx0);
  const HY = (v: number) => hy1 - (Math.min(v, hMaxY) / hMaxY) * (hy1 - hy0);
  const histLine = (sel: (h: HistoryPoint) => number) => hist.map((h, i) => `${i === 0 ? 'M' : 'L'}${HX(i).toFixed(1)},${HY(sel(h)).toFixed(1)}`).join(' ');
  // the RMI line rises to the stale cost, then drops at a retrain
  const rmiPath = hist
    .map((h, i) => {
      const x = HX(i).toFixed(1);
      if (h.retrained && h.rmiBeforeRetrain !== undefined) return `${i === 0 ? 'M' : 'L'}${x},${HY(h.rmiBeforeRetrain).toFixed(1)} L${x},${HY(h.rmi).toFixed(1)}`;
      return `${i === 0 ? 'M' : 'L'}${x},${HY(h.rmi).toFixed(1)}`;
    })
    .join(' ');

  /* ---------- figure 2: the CDF the RMI learns ---------- */
  const CH = 232;
  const px0 = 58;
  const px1 = W - 14;
  const py0 = 14;
  const py1 = CH - 34;
  const kmin = keys[0];
  const kmax = keys[N - 1];
  const KX = (k: number) => px0 + ((k - kmin) / Math.max(1, kmax - kmin)) * (px1 - px0);
  const RY = (r: number) => py1 - (r / Math.max(1, N - 1)) * (py1 - py0);
  const sampleStep = Math.max(1, Math.floor(N / 500));
  let cdf = '';
  for (let i = 0; i < N; i += sampleStep) cdf += `${i === 0 ? 'M' : 'L'}${KX(keys[i]).toFixed(1)},${RY(i).toFixed(1)} `;
  cdf += `L${KX(keys[N - 1]).toFixed(1)},${RY(N - 1).toFixed(1)}`;
  const freshStep = Math.max(1, Math.floor(sim.fresh.length / 300));
  const freshIdx: number[] = [];
  if (sim.fresh.length) {
    let r = 0;
    for (let i = 0; i < sim.fresh.length; i += freshStep) {
      while (r < N && keys[r] < sim.fresh[i]) r++;
      freshIdx.push(r);
    }
  }

  /* ---------- figure 3: probe detail ---------- */
  const winLo = look.lo;
  const winHi = look.hi;
  const w = look.window;
  const stripX0 = 40;
  const stripX1 = W - 40;
  const cellMode = w <= 64;
  const SX = (r: number) => stripX0 + ((r - winLo + (cellMode ? 0 : 0.5)) / (cellMode ? w : Math.max(1, w - 1 + 1))) * (stripX1 - stripX0);
  const cellW = (stripX1 - stripX0) / w;
  const searchShown = look.steps.filter((_, i) => shown(3 + i));
  const cur = searchShown[searchShown.length - 1];
  const searchDone = stage >= maxStage;

  const bitsFrom = Math.max(0, Math.floor(efl.bucketStart / 64) * 64 - (efl.bucketStart % 64 < 16 ? 64 : 0));
  const bitsTo = Math.min(ef.upper.length, bitsFrom + 128);
  const bitW = (W - 60) / 128;
  const examinedLows = Array.from({ length: Math.min(efl.examined, 8) }, (_, j) => {
    const i = efl.bucketStart - efl.v + (efl.examined > 8 ? efl.examined - 8 + j : j);
    return { i, low: ef.lower[i] };
  });

  const detailH = detail === 'rmi' ? 120 : detail === 'ef' ? 150 : 20 + bt.height * 38;

  const legendItems =
    detail === 'rmi'
      ? [
          { label: 'B+tree', color: C_BT },
          { label: 'Elias-Fano', color: C_EF },
          { label: 'RMI: leaf models, window, probes', color: C_RMI },
          { label: 'Keys added since training', color: C_FRESH, shape: 'dot' as const },
          { label: 'Stored keys (the CDF)', color: 'var(--viz-ink-muted)', shape: 'line' as const },
          { label: 'Key found (ink outline)', color: 'var(--viz-ink)', shape: 'line' as const },
        ]
      : detail === 'ef'
        ? [
            { label: 'B+tree', color: C_BT },
            { label: 'Elias-Fano: 1 bits in the upper array', color: C_EF },
            { label: 'RMI', color: C_RMI },
            { label: 'Keys added since training', color: C_FRESH, shape: 'dot' as const },
            { label: 'Key found (ink outline)', color: 'var(--viz-ink)', shape: 'line' as const },
          ]
        : [
            { label: 'B+tree: visited node', color: C_BT },
            { label: 'Elias-Fano', color: C_EF },
            { label: 'RMI', color: C_RMI },
            { label: 'Keys added since training', color: C_FRESH, shape: 'dot' as const },
          ];

  const rmiWorse = rc.avgProbes > bt.probes;
  const lowBits = ef.l;
  const binLow = (v: number) => (lowBits === 0 ? '—' : lowBits <= 8 ? v.toString(2).padStart(lowBits, '0') : fmtNum(v));

  return (
    <VizPanel
      title="One sorted key set, three indexes"
      subtitle="Shape the keys, then look one up. A B+tree descends nodes, an Elias-Fano array jumps to a bucket with select, and a learned RMI predicts a position and searches the window its error bound allows. Append keys to watch the RMI's windows widen until retraining pays."
      controls={
        <>
          <Choice
            label="Key distribution"
            value={dist}
            onChange={(d) => {
              setDist(d);
              if (d === 'sequential' && kind === 'burst') setKind('same');
              rebuild(d, n0, M, F);
            }}
            options={DISTS.map((d) => ({ value: d, label: DIST_LABEL[d] }))}
          />
          <Slider
            label="Keys at build"
            min={1000}
            max={20000}
            step={1000}
            value={n0}
            onChange={(v) => {
              setN0(v);
              setRankPick(Math.floor(v * 0.4));
              rebuild(dist, v, M, F);
            }}
            format={fmtNum}
          />
          <Choice
            label="RMI leaf models"
            value={String(M)}
            onChange={(v) => {
              setM(Number(v));
              rebuild(dist, n0, Number(v), F);
            }}
            options={[4, 16, 64, 256, 1024].map((m) => ({ value: String(m), label: String(m) }))}
          />
          <Choice
            label="B+tree fanout"
            value={String(F)}
            onChange={(v) => {
              setF(Number(v));
              rebuild(dist, n0, M, Number(v));
            }}
            options={[16, 64, 256].map((f) => ({ value: String(f), label: String(f) }))}
          />
        </>
      }
      legend={<Legend items={legendItems} />}
      stats={
        <Stats
          items={[
            { label: 'RMI window, avg / max', value: `${fmtNum(rc.avgWindow, rc.avgWindow >= 100 ? 0 : 1)} / ${fmtNum(rc.maxWindow)}`, hint: 'Slots between pred − below and pred + above (below and above: the farthest any key of that leaf sits from its prediction), averaged over lookups of every stored key.' },
            { label: 'Keys added since training', value: fmtNum(sim.appendedSinceTrain) },
            { label: 'Retrains · keys rescanned', value: `${sim.retrains} · ${fmtNum(sim.retrainScanned)}`, hint: 'A retrain is a full pass over the sorted keys: O(n) per rebuild.' },
            { label: 'Elias-Fano', value: `ℓ = ${ef.l}, ${fmtNum(ec.bitsPerKey, 1)} bits/key`, hint: `Elias's bound for this u/n: 2 + ⌈log2(u/n)⌉ = ${eliasBound} bits, plus select samples.` },
            { label: 'B+tree height', value: `${bt.height} levels`, hint: 'Bulk-loaded with every node full.' },
          ]}
        />
      }
      note={
        <Note>
          {sim.lastEvent ? <strong>{sim.lastEvent} </strong> : null}
          {detail === 'rmi' ? (
            <>
              Key {compact(key)} at rank {fmtNum(rank)}: the root sends it to leaf {look.leaf}, which predicts rank {fmtNum(look.pred)}{look.pred === rank ? ' — exactly right' : `, off by ${fmtNum(Math.abs(look.pred - rank))}`}. The leaf&apos;s error bound makes a window of {fmtNum(w)} slot{w === 1 ? '' : 's'}, closed in {look.steps.length} comparison{look.steps.length === 1 ? '' : 's'} ({look.probes} probes, against {bt.probes} for the B+tree).{' '}
              {rmiWorse ? (auto ? '' : <strong>The stale RMI now costs more than the tree on average: retrain it.</strong>) : sim.appendedSinceTrain > 0 ? `After ${fmtNum(sim.appendedSinceTrain)} new keys the average lookup costs ${fmtNum(rc.avgProbes, 1)} probes, against ${fmtNum(sim.history[0].rmi, 1)} at build.` : ''}
            </>
          ) : detail === 'ef' ? (
            <>
              Key {compact(key)} splits into high part {fmtNum(efl.v)} and a {ef.l}-bit low part. select0({fmtNum(efl.v)}) lands at bit {fmtNum(efl.bucketStart)}, so {fmtNum(r9.rank)} keys have a smaller high part; the bucket holds {fmtNum(efl.bucketSize)} key{efl.bucketSize === 1 ? '' : 's'} and the scan compares {fmtNum(efl.examined)} low part{efl.examined === 1 ? '' : 's'} to reach rank {fmtNum(efl.rank)} ({efl.probes} probes). {ec.maxBucket > 64 ? `The largest bucket holds ${fmtNum(ec.maxBucket)} keys: one ℓ for the whole sequence cannot fit dense runs, and scans inside them are linear.` : ''}
            </>
          ) : (
            <>
              Key {compact(key)} at rank {fmtNum(rank)}: {bt.height} nodes from root to leaf, {bt.comparisons} comparisons and {bt.probes} probes — the same for every key, whatever their distribution. Bulk-loaded full, the nodes above the leaves add {fmtNum(bt.overheadPerKey, 2)} bytes per key.
            </>
          )}
        </Note>
      }
      table={
        <table className="viz-table">
          <thead>
            <tr>
              <th>Structure</th>
              <th>Bytes per key</th>
              <th>Index bytes beyond the 8-byte keys, per key</th>
              <th>Avg probes per lookup</th>
              <th>This lookup: probes</th>
              <th>This lookup: comparisons</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>B+tree (fanout {sim.F}, height {bt.height})</td>
              <td>{fmtNum(bt.bytesPerKey, 3)}</td>
              <td>{fmtNum(bt.overheadPerKey, 3)}</td>
              <td>{fmtNum(bt.probes, 2)}</td>
              <td>{bt.probes}</td>
              <td>{bt.comparisons}</td>
            </tr>
            <tr>
              <td>Elias-Fano (ℓ = {ef.l})</td>
              <td>{fmtNum(ec.bytesPerKey, 3)}</td>
              <td>— the encoding is the keys: {fmtNum(ef.upperBits / ef.n, 2)} upper + {ef.l} lower + {fmtNum(ef.sampleBits / ef.n, 2)} sample bits</td>
              <td>{fmtNum(ec.avgProbes, 2)}</td>
              <td>{efl.probes}</td>
              <td>{efl.examined}</td>
            </tr>
            <tr>
              <td>RMI ({sim.M} leaf models)</td>
              <td>{fmtNum(rc.bytesPerKey, 3)}</td>
              <td>{fmtNum(rc.overheadPerKey, 3)} ({fmtNum(rc.modelBytes)} bytes of models)</td>
              <td>{fmtNum(rc.avgProbes, 2)}</td>
              <td>{look.probes}</td>
              <td>{look.steps.length}</td>
            </tr>
          </tbody>
        </table>
      }
    >
      <div className="viz-controls">
        <Choice label="Append" value={kind} onChange={setKind} options={kinds.map((k) => ({ value: k, label: APPEND_LABEL[k] }))} />
        <Slider label="Keys per append" min={250} max={5000} step={250} value={batch} onChange={setBatch} format={fmtNum} />
        <Button primary onClick={append} disabled={!canAppend}>
          Append keys
        </Button>
        <Button
          onClick={() => {
            setSim((s) => applyOp(s, { type: 'retrain' }, auto));
            setStage(99);
          }}
          disabled={sim.ops >= MAX_OPS || sim.appendedSinceTrain === 0}
        >
          Retrain now
        </Button>
        <Check label="Retrain when the RMI costs more than the B+tree" checked={auto} onChange={setAuto} />
        <Button onClick={() => rebuild(dist, n0, M, F)} disabled={sim.ops === 0}>
          Reset
        </Button>
      </div>

      <svg viewBox={`0 0 ${W} 160`} width={W} height={160} role="img" aria-label={`Meters: bytes per key B+tree ${fmtNum(bt.bytesPerKey, 2)}, Elias-Fano ${fmtNum(ec.bytesPerKey, 2)}, RMI ${fmtNum(rc.bytesPerKey, 2)}; average probes per lookup B+tree ${bt.probes}, Elias-Fano ${fmtNum(ec.avgProbes, 1)}, RMI ${fmtNum(rc.avgProbes, 1)}`}>
        <text x={0} y={12} fontSize={12} fill="var(--viz-ink)">
          Bytes per key
        </text>
        {structs.map((s, i) => (
          <g key={`b${s.name}`}>
            <text x={0} y={30 + i * 18} fontSize={11} fill="var(--viz-ink-2)">
              {s.name}
            </text>
            <rect x={barX} y={20 + i * 18} width={Math.max(2, (s.bytes / bytesMax) * barW)} height={12} rx={2} fill={s.color} />
            <text x={barX + Math.max(2, (s.bytes / bytesMax) * barW) + 5} y={30 + i * 18} fontSize={11} fill="var(--viz-ink)">
              {fmtNum(s.bytes, 2)}
            </text>
          </g>
        ))}
        <text x={0} y={92} fontSize={12} fill="var(--viz-ink)">
          Probes per lookup (avg)
        </text>
        {structs.map((s, i) => (
          <g key={`p${s.name}`}>
            <text x={0} y={110 + i * 18} fontSize={11} fill="var(--viz-ink-2)">
              {s.name}
            </text>
            <rect x={barX} y={100 + i * 18} width={Math.max(2, (Math.min(s.probes, probeMax) / probeMax) * barW)} height={12} rx={2} fill={s.color} />
            <text x={barX + Math.max(2, (Math.min(s.probes, probeMax) / probeMax) * barW) + 5} y={110 + i * 18} fontSize={11} fill="var(--viz-ink)">
              {fmtNum(s.probes, 1)}
            </text>
          </g>
        ))}

        <text x={hx0} y={12} fontSize={12} fill="var(--viz-ink)">
          Avg probes after each operation
        </text>
        {[0, Math.round(hMaxY / 2), hMaxY].map((v) => (
          <g key={`hy${v}`}>
            <line className="viz-grid-line" x1={hx0} x2={hx1} y1={HY(v)} y2={HY(v)} />
            <text x={hx0 - 6} y={HY(v) + 4} fontSize={10} textAnchor="end">
              {v === hMaxY && hClipped ? `${v}+` : v}
            </text>
          </g>
        ))}
        <line className="viz-axis-line" x1={hx0} x2={hx1} y1={hy1} y2={hy1} />
        <text x={(hx0 + hx1) / 2} y={156} fontSize={10} textAnchor="middle">
          operations (appends and retrains) →
        </text>
        {hist.length === 1 ? (
          <text x={(hx0 + hx1) / 2} y={(hy0 + hy1) / 2 - 10} fontSize={11} textAnchor="middle" fill="var(--viz-ink-2)">
            Append keys to plot how each index copes
          </text>
        ) : null}
        <path d={histLine((h) => h.btree)} fill="none" stroke={C_BT} strokeWidth={2} />
        <path d={histLine((h) => h.ef)} fill="none" stroke={C_EF} strokeWidth={2} strokeDasharray="5 3" />
        <path d={rmiPath} fill="none" stroke={C_RMI} strokeWidth={2.5} />
        {hist.map((h, i) => (
          <g key={`hp${i}`}>
            <circle cx={HX(i)} cy={HY(h.btree)} r={2.5} fill={C_BT} />
            <circle cx={HX(i)} cy={HY(h.ef)} r={2.5} fill={C_EF} />
            <circle cx={HX(i)} cy={HY(h.retrained && h.rmiBeforeRetrain !== undefined ? h.rmiBeforeRetrain : h.rmi)} r={3} fill={C_RMI} />
          </g>
        ))}
        {hist.map((h, i) =>
          h.retrained ? (
            <g key={`rt${i}`}>
              <circle cx={HX(i)} cy={HY(h.rmi)} r={4} fill="var(--viz-surface)" stroke={C_RMI} strokeWidth={2} />
              <text x={HX(i)} y={HY(h.rmiBeforeRetrain ?? h.rmi) - 6} fontSize={9} textAnchor="middle" fill="var(--viz-ink-2)">
                retrain
              </text>
            </g>
          ) : null,
        )}
      </svg>

      <svg viewBox={`0 0 ${W} ${CH}`} width={W} height={CH} role="img" aria-label={`Key-to-rank CDF with ${sim.M} RMI leaf models; lookup of key ${compact(key)} predicted at rank ${look.pred}, true rank ${rank}`} style={{ marginTop: 8 }}>
        <text x={px0} y={10} fontSize={12} fill="var(--viz-ink)">
          The CDF the RMI learns: rank against key
        </text>
        <line className="viz-axis-line" x1={px0} x2={px1} y1={py1} y2={py1} />
        <line className="viz-axis-line" x1={px0} x2={px0} y1={py0} y2={py1} />
        <text x={px0 - 6} y={py1} fontSize={10} textAnchor="end">
          0
        </text>
        <text x={px0 - 6} y={py0 + 8} fontSize={10} textAnchor="end">
          {compact(N - 1)}
        </text>
        <text x={14} y={(py0 + py1) / 2} fontSize={10} textAnchor="middle" transform={`rotate(-90 14 ${(py0 + py1) / 2})`}>
          rank
        </text>
        <text x={px0} y={py1 + 14} fontSize={10}>
          {compact(kmin)}
        </text>
        <text x={px1} y={py1 + 14} fontSize={10} textAnchor="end">
          {compact(kmax)}
        </text>
        <text x={(px0 + px1) / 2} y={py1 + 26} fontSize={10} textAnchor="middle">
          key →
        </text>
        <rect x={px0 + 1} y={Math.min(RY(winLo), RY(winHi)) - 1.5} width={px1 - px0 - 1} height={Math.max(3, Math.abs(RY(winLo) - RY(winHi)) + 3)} fill={C_RMI} fillOpacity={0.22} />
        {freshIdx.map((r, i) => (
          <circle key={`f${i}`} cx={KX(keys[r])} cy={RY(r)} r={2.2} fill={C_FRESH} />
        ))}
        {sim.model.leaves.map((_, j) => {
          const a = ranges.first[j];
          const b = ranges.last[j];
          if (a < 0) return null;
          return <line key={`l${j}`} x1={KX(keys[a])} x2={KX(keys[b]) + (a === b ? 1.5 : 0)} y1={RY(predict(sim.model, keys[a], N))} y2={RY(predict(sim.model, keys[b], N))} stroke={C_RMI} strokeWidth={3.5} strokeLinecap="round" strokeOpacity={0.85} />;
        })}
        <path d={cdf} fill="none" stroke="var(--viz-ink-muted)" strokeWidth={1.2} />
        <line x1={KX(key)} x2={KX(key)} y1={py0} y2={py1} stroke="var(--viz-ink-2)" strokeDasharray="4 3" />
        <circle cx={KX(key)} cy={RY(look.pred)} r={6} fill="none" stroke={C_RMI} strokeWidth={2.5} />
        <circle cx={KX(key)} cy={RY(rank)} r={3} fill="var(--viz-ink)" />
        <text x={KX(key) > (px0 + px1) / 2 ? KX(key) - 10 : KX(key) + 10} y={Math.max(py0 + 22, Math.min(py1 - 6, RY(rank) - 8))} fontSize={10} textAnchor={KX(key) > (px0 + px1) / 2 ? 'end' : 'start'} fill="var(--viz-ink)" stroke="var(--viz-surface)" strokeWidth={3} paintOrder="stroke">
          lookup: rank {fmtNum(rank)}, predicted {fmtNum(look.pred)}
        </text>
      </svg>

      <div className="viz-controls" style={{ marginTop: 8 }}>
        <Slider label="Look up the key at rank" min={0} max={N - 1} value={rank} onChange={(v) => { setRankPick(v); setStage(99); setRunning(false); }} format={fmtNum} />
        <Button
          onClick={() => {
            const next = picks + 1;
            setPicks(next);
            setRankPick(Math.floor(makeRng(next * 7919 + 13)() * N));
            setStage(99);
            setRunning(false);
          }}
        >
          Another key
        </Button>
        <Segmented
          label="Probe detail"
          value={detail}
          onChange={(d) => {
            setDetail(d);
            setStage(99);
            setRunning(false);
          }}
          options={[
            { value: 'rmi', label: 'RMI' },
            { value: 'ef', label: 'Elias-Fano' },
            { value: 'bt', label: 'B+tree' },
          ]}
        />
        <Button
          primary
          onClick={() => {
            acc.current = 0;
            setStage(0);
            setRunning(true);
          }}
        >
          Animate lookup
        </Button>
        <Button
          onClick={() => {
            setRunning(false);
            setStage((s) => (s >= maxStage ? 0 : s + 1 >= maxStage ? 99 : s + 1));
          }}
        >
          Step
        </Button>
      </div>

      <svg viewBox={`0 0 ${W} ${detailH}`} width={W} height={detailH} role="img" aria-label={detail === 'rmi' ? `RMI search window of ${w} slots from rank ${winLo} to ${winHi}` : detail === 'ef' ? `Elias-Fano upper bits around bucket ${efl.v}` : `B+tree descent through ${bt.height} levels`}>
        {detail === 'rmi' ? (
          <>
            <text x={stripX0} y={12} fontSize={11} fill="var(--viz-ink)">
              Whole array, 0 … {fmtNum(N - 1)}
            </text>
            <rect x={stripX0} y={18} width={stripX1 - stripX0} height={6} rx={2} fill="var(--viz-plane)" stroke="var(--viz-border)" strokeWidth={0.5} />
            {shown(2) ? <rect x={stripX0 + (winLo / N) * (stripX1 - stripX0)} y={15} width={Math.max(3, (w / N) * (stripX1 - stripX0))} height={12} fill={C_RMI} /> : null}
            {shown(1) ? <line x1={stripX0 + (look.pred / N) * (stripX1 - stripX0)} x2={stripX0 + (look.pred / N) * (stripX1 - stripX0)} y1={12} y2={30} stroke="var(--viz-ink)" strokeWidth={1.5} /> : null}
            <text x={stripX0} y={48} fontSize={11} fill="var(--viz-ink)">
              {shown(2) ? `Search window: ranks ${fmtNum(winLo)} … ${fmtNum(winHi)} (pred − ${fmtNum(look.pred - winLo)}, pred + ${fmtNum(winHi - look.pred)})` : shown(1) ? `Leaf ${look.leaf} predicts rank ${fmtNum(look.pred)}` : `Root model picks leaf ${look.leaf} of ${sim.M}`}
            </text>
            {shown(2)
              ? cellMode
                ? Array.from({ length: w }, (_, c) => {
                    const r = winLo + c;
                    const inCur = cur ? r >= cur.lo && r <= cur.hi : true;
                    const found = searchDone && r === look.rank;
                    return <rect key={`c${c}`} x={stripX0 + c * cellW + 0.5} y={56} width={Math.max(1, cellW - 1)} height={20} rx={1.5} fill={inCur ? 'var(--viz-surface)' : 'var(--viz-plane)'} stroke={found ? 'var(--viz-ink)' : r === look.pred ? C_RMI : 'var(--viz-border)'} strokeWidth={found ? 3 : r === look.pred ? 2 : 0.6} />;
                  })
                : (
                  <>
                    <rect x={stripX0} y={56} width={stripX1 - stripX0} height={20} rx={2} fill="var(--viz-plane)" stroke="var(--viz-border)" strokeWidth={0.6} />
                    {cur ? <rect x={SX(cur.lo)} y={56} width={Math.max(2, SX(cur.hi + 1) - SX(cur.lo))} height={20} fill="var(--viz-surface)" stroke={C_RMI} strokeWidth={1} /> : null}
                    {searchDone ? <rect x={SX(look.rank) - 2} y={53} width={4} height={26} fill="var(--viz-ink)" /> : null}
                    <line x1={SX(look.pred)} x2={SX(look.pred)} y1={52} y2={80} stroke={C_RMI} strokeWidth={2} />
                  </>
                )
              : null}
            {(() => {
              const labelled: number[] = [];
              return searchShown.map((s, k) => {
                const x = cellMode ? stripX0 + (s.mid - winLo + 0.5) * cellW : SX(s.mid);
                const isLast = k === searchShown.length - 1;
                const free = labelled.every((lx) => Math.abs(lx - x) > 16);
                const label = free || isLast;
                if (free) labelled.push(x);
                return (
                  <g key={`s${k}`}>
                    <line x1={x} x2={x} y1={78} y2={86 + (k % 2) * 10} stroke={C_RMI} strokeWidth={1.5} />
                    {label ? (
                      <text x={x} y={96 + (k % 2) * 10} fontSize={9} textAnchor="middle" fill="var(--viz-ink-2)">
                        {free ? k + 1 : `…${k + 1}`}
                      </text>
                    ) : null}
                  </g>
                );
              });
            })()}
            {shown(2) ? (
              <text x={stripX1} y={116} fontSize={10} textAnchor="end" fill="var(--viz-ink-2)">
                {searchDone ? `found at rank ${fmtNum(look.rank)} after ${look.steps.length} comparisons` : `comparison ${searchShown.length} of ${look.steps.length}`}
              </text>
            ) : null}
          </>
        ) : detail === 'ef' ? (
          <>
            <text x={30} y={12} fontSize={11} fill="var(--viz-ink)">
              Upper bits {fmtNum(bitsFrom)} … {fmtNum(bitsTo - 1)} of {fmtNum(ef.upper.length)}: a 1 per key, a 0 closing each high part
            </text>
            {Array.from({ length: bitsTo - bitsFrom }, (_, c) => {
              const p = bitsFrom + c;
              return <rect key={`u${c}`} x={30 + c * bitW + 0.4} y={22} width={Math.max(1, bitW - 0.8)} height={18} fill={ef.upper[p] ? C_EF : 'var(--viz-plane)'} stroke="var(--viz-border)" strokeWidth={0.4} />;
            })}
            {shown(1) && efl.bucketSize > 0 && efl.bucketStart < bitsTo ? (
              <path
                d={`M${30 + (Math.max(bitsFrom, efl.bucketStart) - bitsFrom) * bitW},41 v4 H${30 + (Math.min(bitsTo, efl.bucketStart + efl.bucketSize) - bitsFrom) * bitW} v-4`}
                fill="none"
                stroke="var(--viz-ink)"
                strokeWidth={2}
              />
            ) : null}
            {[bitsFrom, bitsFrom + 64, bitsFrom + 128].map((p) => (
              <g key={`wb${p}`}>
                <line x1={30 + (p - bitsFrom) * bitW} x2={30 + (p - bitsFrom) * bitW} y1={18} y2={46} stroke="var(--viz-ink-2)" strokeWidth={p % 512 === 0 ? 2 : 1} />
                {p < bitsTo ? (
                  <text x={32 + (p - bitsFrom) * bitW} y={56} fontSize={9}>
                    {p % 512 === 0 ? `block + word ${fmtNum(p / 64)}` : `word ${fmtNum(p / 64)}`}
                  </text>
                ) : null}
              </g>
            ))}
            {shown(1) && efl.bucketStart >= bitsFrom && efl.bucketStart <= bitsTo ? (
              <g>
                <path d={`M${30 + (efl.bucketStart - bitsFrom) * bitW},46 l-4,8 l8,0 z`} fill="var(--viz-ink)" />
                <text x={Math.min(W - 160, 30 + (efl.bucketStart - bitsFrom) * bitW + 8)} y={70} fontSize={10} fill="var(--viz-ink)">
                  select0({fmtNum(efl.v)}) = bit {fmtNum(efl.bucketStart)}
                </text>
              </g>
            ) : null}
            {shown(3) ? (
              <>
                <text x={30} y={96} fontSize={11} fill="var(--viz-ink)">
                  Low parts scanned in this bucket (ℓ = {ef.l} bits), against the key&apos;s low part {binLow(efl.xl)}:
                </text>
                {examinedLows.map((e, j) => {
                  const found = e.i === efl.rank;
                  return (
                    <g key={`lo${j}`}>
                      <rect x={30 + j * 78} y={104} width={72} height={22} rx={3} fill="var(--viz-surface)" stroke={found ? 'var(--viz-ink)' : C_EF} strokeWidth={found ? 3 : 1.2} />
                      <text x={66 + j * 78} y={119} fontSize={10} textAnchor="middle" fill="var(--viz-ink)">
                        {binLow(e.low)}
                      </text>
                    </g>
                  );
                })}
                {efl.examined === 0 ? (
                  <text x={30} y={120} fontSize={10}>
                    empty bucket: the answer is the next key
                  </text>
                ) : null}
                <text x={30} y={144} fontSize={10} fill="var(--viz-ink-2)">
                  {efl.examined > 8 ? `…the last 8 of ${fmtNum(efl.examined)} comparisons shown` : `${efl.examined} comparison${efl.examined === 1 ? '' : 's'}`}; rank = {fmtNum(efl.rank)}
                </text>
              </>
            ) : null}
          </>
        ) : (
          <>
            {bt.levels.map((lv, l) => {
              const y = 10 + l * 38;
              const visited = path[l];
              const showNodes = 7;
              const startIdx = Math.max(0, Math.min(lv.nodes - showNodes, visited - 3));
              const endIdx = Math.min(lv.nodes, startIdx + showNodes);
              const reached = shown(l);
              return (
                <g key={`lv${l}`}>
                  <text x={0} y={y + 17} fontSize={11} fill="var(--viz-ink)">
                    {l === 0 ? 'root' : lv.inner ? 'inner' : 'leaf'}
                  </text>
                  <text x={0} y={y + 29} fontSize={9}>
                    {fmtNum(lv.nodes)} node{lv.nodes === 1 ? '' : 's'}
                  </text>
                  {startIdx > 0 ? (
                    <text x={70} y={y + 17} fontSize={11}>
                      …
                    </text>
                  ) : null}
                  {Array.from({ length: endIdx - startIdx }, (_, c) => {
                    const idx = startIdx + c;
                    const hit = reached && idx === visited;
                    return (
                      <g key={`n${idx}`}>
                        <rect x={84 + c * 52} y={y} width={46} height={24} rx={3} fill="var(--viz-surface)" stroke={hit ? C_BT : 'var(--viz-border)'} strokeWidth={hit ? 2.5 : 0.8} />
                        <text x={107 + c * 52} y={y + 16} fontSize={9} textAnchor="middle" fill={hit ? 'var(--viz-ink)' : 'var(--viz-ink-muted)'}>
                          #{fmtNum(idx)}
                        </text>
                      </g>
                    );
                  })}
                  {endIdx < lv.nodes ? (
                    <text x={84 + (endIdx - startIdx) * 52} y={y + 17} fontSize={11}>
                      …
                    </text>
                  ) : null}
                  {reached ? (
                    <text x={W - 4} y={y + 16} fontSize={10} textAnchor="end" fill="var(--viz-ink-2)">
                      {fmtNum(lv.entries)} entries: {lv.comparisons} comparison{lv.comparisons === 1 ? '' : 's'}, {lv.lines} probe{lv.lines === 1 ? '' : 's'}
                    </text>
                  ) : null}
                </g>
              );
            })}
          </>
        )}
      </svg>

      <ol style={{ margin: '0.4rem 0 0', paddingLeft: '1.2rem', fontSize: '0.8rem', display: 'grid', gap: 3, color: 'var(--viz-ink)' }}>
        {detail === 'rmi' ? (
          <>
            <li>
              Root model: f0({compact(key)}) scaled by {sim.M}/{fmtNum(sim.model.nTrain)} picks leaf {look.leaf}.
            </li>
            {shown(1) ? <li>Leaf {look.leaf}: slope and intercept predict rank {fmtNum(look.pred)}.</li> : null}
            {shown(2) ? (
              <li>
                Its stored errors — true rank at most {fmtNum(rc.errs[look.leaf].below)} below the prediction and {fmtNum(rc.errs[look.leaf].above)} above
                {sim.appendedSinceTrain > 0 ? ' (what the stale model now needs, after the appends)' : ''} — bound the window to {fmtNum(w)} slots.
              </li>
            ) : null}
            {shown(3) ? (
              <li>
                Binary search inside the window, first probe at the prediction: {look.steps.length} comparison{look.steps.length === 1 ? '' : 's'}, {searchLines(w)} cache line{searchLines(w) === 1 ? '' : 's'} of keys.
              </li>
            ) : null}
          </>
        ) : detail === 'ef' ? (
          <>
            <li>
              Split the key: high part {fmtNum(key)} ≫ {ef.l} = {fmtNum(efl.v)}; low part = the bottom {ef.l} bits.
            </li>
            {shown(1) ? (
              <li>
                select0({fmtNum(efl.v)}): jump to sample #{efl.sample} (one per {SELECT_SAMPLE} zeros), then popcount forward {fmtNum(efl.scanned)} bits to bit {fmtNum(efl.bucketStart)}.
              </li>
            ) : null}
            {shown(2) ? (
              <li>
                rank1(bit {fmtNum(efl.bucketStart)}) = block count {fmtNum(r9.block)} + word count {fmtNum(r9.word)} + popcount in the word {fmtNum(r9.inWord)} = {fmtNum(r9.rank)} keys before this bucket (= bit − high part).
              </li>
            ) : null}
            {shown(3) ? (
              <li>
                Scan the bucket&apos;s {fmtNum(efl.bucketSize)} low part{efl.bucketSize === 1 ? '' : 's'} in order until one is ≥ the key&apos;s: {fmtNum(efl.examined)} read, rank {fmtNum(efl.rank)}.
              </li>
            ) : null}
          </>
        ) : (
          bt.levels.map((lv, l) =>
            shown(l) ? (
              <li key={`bl${l}`}>
                {l === 0 ? 'Root' : lv.inner ? 'Inner node' : 'Leaf'} #{fmtNum(path[l])}: binary search over {fmtNum(lv.entries)} {lv.inner ? 'separators, then read the child pointer' : 'keys'}.
              </li>
            ) : null,
          )
        )}
      </ol>
    </VizPanel>
  );
}
